export const GET_PEOPLE = 'GET_PEOPLE';
export const SET_RESULTS_LOADING = 'SET_RESULTS_LOADING';
export const GET_VEHICLE = 'GET_VEHICLE';
export const GET_USER = 'GET_USER';
export const SET_VEHICLE_RESULTS_LOADING = 'SET_VEHICLE_RESULTS_LOADING';

